[package]
name = "font-mud"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.20"
msdfgen = {version = "0.2.1", default-features = false, features = ["ttf-parser", "png"]}
ttf-parser = "0.18.1"
rect_packer = "0.2.1"

[dev-dependencies]
png = "0.17"