[package]
name = "hearth-ipc"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
hearth-rpc = { workspace = true }
tokio = { version = "1.24", features = ["net"] }
tracing = { workspace = true }
