[package]
name = "hearth-daemon"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
hearth-core = { workspace = true }
hearth-init = { workspace = true }
hearth-ipc = { workspace = true }
tracing = { workspace = true }
