[package]
name = "hearth-test-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hearth-guest = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
