[package]
name = "hearth-rpc"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
hearth-types = { workspace = true }
serde = { workspace = true }
tokio = { version = "1.24", features = ["sync"] }

[features]
mocks = []
