[package]
name = "hearth-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
hearth-network = { workspace = true }
hearth-rpc = { workspace = true }
tokio = { version = "1.24", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["fmt"] }
