name: Update Depgraph

on:
  workflow_dispatch:
  push:
    paths: [ "**/Cargo.toml" ]
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  depgraph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.ADMIN_PAT }}
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Install graphviz
      run: sudo apt install graphviz
    - name: Generate depgraph
      run: cargo run -p hearth-depgraph > depgraph.dot
    - name: Visualize depgraph
      run: dot -Tpng depgraph.dot > resources/misc/depgraph.png
    - name: Commit depgraph
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: 'readme: update depgraph'
          file_pattern: 'resources/misc/depgraph.png'
