name: Pull Request Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hearth-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets
  hearth-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-targets
  hearth-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Swatinem/rust-cache@v2.2.0
    - run: rustup component add clippy
    - uses: clechasseur/rs-clippy-check@v3
      with:
        args: --all-targets
  hearth-rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - uses: LoliGothick/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: hearth_rustfmt
        flags: --all
  kindling-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2.2.0
      with:
        workspaces: "kindling -> kindling/target"
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets --manifest-path kindling/Cargo.toml --target wasm32-unknown-unknown
  kindling-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: rustup target add wasm32-unknown-unknown
    - run: rustup component add clippy
    - uses: Swatinem/rust-cache@v2.2.0
      with:
        workspaces: "kindling -> kindling/target"
    - uses: clechasseur/rs-clippy-check@v3
      with:
        working-directory: "kindling"
        args: --all-targets --target wasm32-unknown-unknown
  kindling-rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - uses: LoliGothick/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: kindling_rustfmt
        working-directory: "kindling"
        flags: --all
